apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      kubernetes.io/cluster-service: "true"
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.11
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
          protocol: TCP
        env:
        - name: FLUENTD_HOST
          value: 1.1.1.1          #* customize with your fluentd host IP here
        - name: FLUENTD_PORT
          value: "30855"
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 50Mi
        #   requests:
        #     cpu: 100m
        #     memory: 50Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log          
        - name: varnutanixdockercontainers
          mountPath: /var/nutanix/docker/containers
          readOnly: true
        - name: journald-path
          mountPath: /run/log/journal          
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/          
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      priorityClassName: ntnx-system-node-critical
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule        
      - operator: Exists
        effect: NoExecute        
      - operator: Exists
        effect: NoSchedule        
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varnutanixdockercontainers
        hostPath:
          path: /var/nutanix/docker/containers
      - name: journald-path
        hostPath:
          path: /run/log/journal        
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config        
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate