apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         3
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    @INCLUDE input-kube-system.conf
    @INCLUDE input-ntnx-logging.conf
    @INCLUDE input-systemd.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-systemd.conf
    @INCLUDE output-kubernetes-elasticsearch.conf
    @INCLUDE output-fluentd-forward.conf

  input-kube-system.conf: |
    [INPUT]
        Name                tail
        Tag                 kubernetes.*
        Path                /var/log/containers/*kube-system*.log
        Parser              docker
        DB                  /var/log/aggr_flb_kube.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10

  input-ntnx-logging.conf: |
    [INPUT]
        Name                tail
        Tag                 kubernetes.*
        Path                /var/log/containers/*ntnx-system*.log
        Parser              docker
        DB                  /var/log/aggr_flb_ntnx.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10

  input-systemd.conf: |
    [INPUT]
        Name                systemd
        Tag                 host.*
        Systemd_Filter      _SYSTEMD_UNIT=docker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet-worker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet-master.service
        Systemd_Filter      _SYSTEMD_UNIT=etcd.service
        Systemd_Filter      _SYSTEMD_UNIT=keepalived.service
        DB                  /var/log/aggr_flb_systemd.db

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kubernetes.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        tls.verify          Off

  filter-systemd.conf: |
    [FILTER]
        Name                record_modifier
        Match               host.*
        Remove_key          _SYSTEMD_CGROUP
        Remove_key          _SYSTEMD_SLICE
        Remove_key          _SYSLOG_IDENTIFIER
        Remove_key          _BOOT_ID
        Remove_key          _CAP_EFFECTIVE
        Remove_key          _COMM
        Remove_key          _MACHINE_ID

  output-kubernetes-elasticsearch.conf: |
    # [OUTPUT]
    #     Name                es
    #     Match               kubernetes.*
    #     Host                ${FLUENT_ELASTICSEARCH_HOST}
    #     Port                ${FLUENT_ELASTICSEARCH_PORT}
    #     Logstash_Format     On
    #     Replace_Dots        On
    #     Retry_Limit         5
    #     Logstash_Prefix	    kubernetes

  output-fluentd-forward.conf: |
    [OUTPUT]
        Name                  forward
        Match                 *
        Host                  ${FLUENTD_HOST}
        Port                  ${FLUENTD_PORT}
        

  parsers.conf: |
    [PARSER]
        Name        apache
        Format      regex
        Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        apache2
        Format      regex
        Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        apache_error
        Format      regex
        Regex       ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name        nginx
        Format      regex
        Regex       ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S